import type { RichLesson } from '../lessonTypes'

export const chapter2: RichLesson = {
  id: 'S02',
  title: 'One Wrong Tone and You Just Said WHAT',
  goal: 'Learn words where a slight tonal shift turns an innocent sentence into a catastrophe, an insult, or an accidental proposition.',
  phase: 'vowels',
  order: 1,
  difficulty: 'beginner',
  prerequisites: [],
  steps: [
    {
      kind: 'text',
      content:
        'Thai has 5 tones. Get one wrong and \'beautiful\' becomes \'unlucky,\' \'near\' becomes \'far,\' and \'rice\' becomes something your grandmother would slap you for saying. These are the tonal landmines that every foreigner steps on. Repeatedly. While Thai people try not to laugh. And fail.',
    },
    {
      kind: 'table',
      title: 'Tonal Disasters',
      headers: ['Correct', 'Romanization', 'Meaning', 'Wrong Tone', 'Wrong Meaning', 'What Happens'],
      rows: [
        [
          'สวย',
          'suuai (rising)',
          'Beautiful',
          'ซวย suuai (falling)',
          'Unlucky',
          'You told her she\'s UNLUCKY. She was expecting a compliment. You are now single.',
        ],
        [
          'ใกล้',
          'glai (falling)',
          'Near',
          'ไกล glai (mid)',
          'Far',
          'You asked "Is it near?" They said "Yes, near." You heard "far" and walked 3km the wrong direction.',
        ],
        [
          'ข้าว',
          'khaao (falling)',
          'Rice',
          'เข้า khao (rising)',
          'To enter',
          'You asked to enter the rice. The vendor is staring.',
        ],
        [
          'หมา',
          'maa (rising)',
          'Dog',
          'ม้า maa (high)',
          'Horse',
          '"I have two cute dogs at home" -> "I have two cute horses at home." Pet shop guy checks if you\'re serious.',
        ],
        [
          'สี่',
          'sii (low)',
          'Four',
          'ซี้ sii (high)',
          'Very close friend / dead',
          'Asking for 4 somethings but accidentally saying something died. Chaos at the market.',
        ],
        [
          'เผา',
          'phao (rising)',
          'To burn/grill',
          'เผ่า phao (low)',
          'Tribe',
          'Ordering "grilled chicken" but saying "tribe chicken." Anthropology, not dinner.',
        ],
        [
          'คาง',
          'khaang (mid)',
          'Chin',
          'ค้าง khaang (high)',
          'Stuck/overnight',
          '"Your chin is beautiful" -> "You stayed overnight beautifully." Romantic? Creepy? Both?',
        ],
        [
          'สุก',
          'suk (low)',
          'Ripe/cooked',
          'ศึก suek (low)',
          'War',
          '"Is the mango ripe?" -> "Is the mango war?" The fruit vendor has questions.',
        ],
        [
          'พริก',
          'phrik (low)',
          'Chili',
          'พริ้ง phring (high)',
          'Pretty/charming',
          '"More chili please" -> "More pretty please." The vendor is flattered but confused.',
        ],
      ],
    },
    {
      kind: 'table',
      title: 'What You Meant vs What You Actually Said',
      headers: ['What You Meant to Say', 'What Came Out of Your Mouth', 'Aftermath'],
      rows: [
        [
          'คุณสวยมาก (You\'re very beautiful)',
          'คุณซวยมาก (You\'re very unlucky)',
          'She walks away. You wonder what went wrong. Everything. Everything went wrong.',
        ],
        [
          'มันใกล้ไหม (Is it near?)',
          'มันไกลไหม (Is it far?)',
          'You asked the opposite question and got directions to the opposite place. You\'re now in a different province.',
        ],
        [
          'ผมอยากได้หมา (I want a dog)',
          'ผมอยากได้ม้า (I want a horse)',
          'The pet shop lady calls her husband for backup.',
        ],
        [
          'ขอข้าวผัดหนึ่งจาน (One fried rice please)',
          'ขอเข้าผัดหนึ่งจาน (One enter-stir-fry please)',
          'The cook stares. You point at the menu. Crisis averted. Dignity not averted.',
        ],
        [
          'มีหมาสองตัว (I have two dogs)',
          'มีม้าสองตัว (I have two horses)',
          'Your neighbor now thinks you\'re rich and starts being suspiciously friendly.',
        ],
      ],
    },
    {
      kind: 'dialogue',
      title: 'The Tonal Disaster Date',
      lines: [
        {
          speaker: 'Him',
          thai: 'คุณสวยมาก',
          romanization: 'khun suuai maak',
          english: 'You\'re very beautiful',
        },
        {
          speaker: 'Her',
          thai: 'ขอบคุณค่ะ',
          romanization: 'khawp-khun kha',
          english: 'Thank you',
        },
        {
          speaker: 'Him',
          thai: 'อยากกินข้าว... เอ่อ...',
          romanization: 'yaak gin khaao... oe...',
          english: 'Want to eat ri-- uh... (wrong tone)',
        },
        {
          speaker: 'Her',
          thai: 'อะไรนะ',
          romanization: 'a-rai na',
          english: 'What?',
        },
        {
          speaker: 'Him',
          thai: 'ข้าว! ข้าว! RICE!',
          romanization: 'khaao! khaao! RICE!',
          english: 'Rice! Rice! RICE!',
        },
        {
          speaker: 'Her',
          thai: '555 ฝรั่งน่ารัก',
          romanization: 'hahaha farang naa-rak',
          english: 'Hahaha cute farang',
        },
        {
          speaker: 'Him',
          thai: 'มีหมาน่ารัก...',
          romanization: 'mii maa naa-rak...',
          english: 'I have a cute dog-- (wrong tone)',
        },
        {
          speaker: 'Her',
          thai: 'ม้าหรอ? มีม้าที่ไหน!',
          romanization: 'maa raw? mii maa thii nai!',
          english: 'A horse?! Where do you keep a horse?!',
        },
        {
          speaker: 'Him',
          thai: '...กูยอมแพ้แม่ง',
          romanization: '...guu yawm-phae maeng',
          english: '...I f*cking give up',
        },
      ],
    },
  ],
  assessment: [
    {
      type: 'multiple_choice',
      prompt: 'You want to say \'beautiful\' (สวย). Wrong tone gives you...',
      options: ['ซวย (unlucky)', 'Happy', 'Delicious', 'Tall'],
      correctIndex: 0,
    },
    {
      type: 'multiple_choice',
      prompt: 'ใกล้ means \'near.\' ไกล means...',
      options: ['Also near', 'Far (the exact opposite)', 'Beautiful', 'Spicy'],
      correctIndex: 1,
    },
    {
      type: 'multiple_choice',
      prompt: 'You proudly tell someone หมาของผมน่ารัก. But with wrong tone it becomes...',
      options: ['My horse is cute', 'My dog is cute', 'My cat is cute', 'My chin is cute'],
      correctIndex: 0,
    },
    {
      type: 'multiple_choice',
      prompt: 'Which tonal disaster is most likely to end a first date?',
      options: ['ข้าว/เข้า', 'สวย/ซวย', 'หมา/ม้า', 'สี่/ซี้'],
      correctIndex: 1,
    },
    {
      type: 'multiple_choice',
      prompt: 'How many tones does Thai have?',
      options: ['3', '4', '5', '7'],
      correctIndex: 2,
    },
    {
      type: 'multiple_choice',
      prompt: 'A foreigner says คุณซวยมาก to a Thai woman. What did he accidentally tell her?',
      options: [
        'You\'re very beautiful',
        'You\'re very unlucky',
        'You\'re very tall',
        'You\'re very kind',
      ],
      correctIndex: 1,
    },
  ],
  srsItemIds: [],
}
