import type { RichLesson } from '../lessonTypes'

export const chapter3: RichLesson = {
  id: 'S03',
  title: 'The Thai Zoological Guide to Telling People They Suck',
  goal: 'Master the Thai art of animal-based insults -- the most culturally rich and creative way to tell someone exactly what you think of them.',
  phase: 'reading',
  order: 2,
  difficulty: 'beginner',
  prerequisites: [],
  steps: [
    {
      kind: 'text',
      content:
        'Forget Shakespeare. Thai people have perfected the art of the insult using the animal kingdom. ควาย (buffalo) = you\'re an idiot. หมู (pig) = you\'re a disgusting slob. เหี้ย (monitor lizard) = you are the lowest form of life. Each animal carries a surgically precise insult. By the end of this chapter you\'ll be able to construct Thai insults with the vocabulary of a Bangkok taxi driver.',
    },
    {
      kind: 'table',
      title: 'Animal Insult Encyclopedia',
      headers: ['Thai', 'Romanization', 'Animal', 'Insult Meaning', 'Example'],
      rows: [
        [
          'ควาย',
          'khwaai',
          'Buffalo',
          'Stupid / thick-skulled',
          'The undisputed king of Thai insults. "ไอ้ควาย!" = "You absolute moron!" Heard in traffic approximately 400 times per day in Bangkok.',
        ],
        [
          'หมู',
          'muu',
          'Pig',
          'Greedy / messy / lazy',
          '"กินเหมือนหมู" = "Eats like a pig." Also: "อ้วนเหมือนหมู" = "Fat as a pig." Not subtle.',
        ],
        [
          'ลิง',
          'ling',
          'Monkey',
          'Hyperactive / annoying / can\'t sit still',
          'For children AND adults who act like children. "นั่งนิ่งๆ สิ ไอ้ลิง!" = "Sit still, you monkey!"',
        ],
        [
          'หมา',
          'maa',
          'Dog',
          'Shameless / low',
          '"อย่าทำตัวเหมือนหมา" = "Don\'t act like a dog." Reserved for people with zero dignity.',
        ],
        [
          'งู',
          'nguu',
          'Snake',
          'Two-faced / backstabber',
          '"ระวัง เขาเป็นงู" = "Watch out, she\'s a snake." For the coworker who smiles at you then talks behind your back.',
        ],
        [
          'จระเข้',
          'jaw-ra-khee',
          'Crocodile',
          'Womanizer / player',
          'For men who flirt with anything that moves. "ไอ้จระเข้!" = every Thai soap opera, every episode.',
        ],
        [
          'แมงดา',
          'maeng-daa',
          'Horseshoe crab',
          'Man who lives off women\'s money',
          'Extremely specific, extremely cutting. Thai women use this like a scalpel.',
        ],
        [
          'กบ',
          'gop',
          'Frog',
          'Brags beyond ability',
          'The guy who claims he can fight but runs when trouble starts. All croak, no bite.',
        ],
        [
          'เต่า',
          'dtao',
          'Turtle',
          'Painfully slow',
          '"เร็วหน่อยสิ ไอ้เต่า!" = "MOVE IT, you turtle!" Said to every slow driver in Thailand.',
        ],
        [
          'ไก่',
          'gai',
          'Chicken',
          'Coward',
          '"ไก่อ่อน" = chicken, pushover, easy target. Also used for scam victims.',
        ],
        [
          'หมูหมา',
          'muu-maa',
          'Pig-dog (combo)',
          'Worthless / beneath contempt',
          'When one animal isn\'t enough.',
        ],
        [
          'อีแร้ง',
          'ii-raeng',
          'Vulture',
          'Opportunist / scavenger',
          'For people who show up only when there\'s something to gain.',
        ],
      ],
    },
    {
      kind: 'table',
      title: 'Key Phrases',
      headers: ['Thai', 'Romanization', 'English'],
      rows: [
        ['ไอ้ควาย เร็วหน่อยสิโว้ย', 'ai khwaai rew noi si wooi', 'HURRY UP you f*cking buffalo!'],
        ['กินเหมือนหมูสัส', 'gin muean muu sat', 'Eats like a damn pig'],
        ['อย่าเป็นไก่อ่อนสิ', 'yaa bpen gai on si', 'Don\'t be such a chicken, come on'],
        ['ระวังนะ ไอ้จระเข้ตัวนั้น', 'ra-wang na ai jaw-ra-khee dtua nan', 'Watch out for that crocodile (player)'],
        ['มึงเป็นลิงหรอ นั่งนิ่งๆ สิสัส', 'mueng bpen ling raw, nang ning ning si sat', 'Are you a damn monkey? SIT STILL'],
        ['ช้าเหมือนเต่าแม่ง', 'chaa muean dtao maeng', 'Slow as a f*cking turtle'],
        ['ไอ้แมงดา หาเงินเองบ้างสิ', 'ai maeng-daa haa ngoen eng baang si', 'You leech, earn your own damn money'],
      ],
    },
    {
      kind: 'dialogue',
      title: 'Bangkok Taxi Road Rage',
      lines: [
        {
          speaker: 'Taxi Driver',
          thai: 'เฮ้ย ไอ้ควาย! ขับรถเป็นไหมห่า!',
          romanization: 'hoei ai khwaai! khap rot bpen mai haa!',
          english: 'HEY buffalo! Can you even f*cking drive?!',
        },
        {
          speaker: 'Other Driver',
          thai: 'โว้ย! มึงตาบอดหรอสัส ไฟแดงอยู่!',
          romanization: 'wooi! mueng dtaa bawt raw sat fai daeng yuu!',
          english: 'OI! Are you blind, dammit? It\'s a red light!',
        },
        {
          speaker: 'Taxi Driver',
          thai: 'อ้าว กูเห็น แต่มึงช้าเหมือนเต่า ถ้าช้ากว่านี้ต้องถอยหลัง',
          romanization: 'aao guu hen dtae mueng chaa muean dtao thaa chaa gwaa nii dtawng thoi lang',
          english: 'I saw it, but you\'re so slow you\'d have to go backwards to be any slower',
        },
        {
          speaker: 'Other Driver',
          thai: 'ไอ้จระเข้ปากดี',
          romanization: 'ai jaw-ra-khee bpaak dii',
          english: 'You\'re a real loudmouth crocodile',
        },
        {
          speaker: 'Taxi Driver',
          thai: 'ไอ้ลิง จะมาสอนกูขับรถหรอ',
          romanization: 'ai ling ja maa sawn guu khap rot raw',
          english: 'You monkey, you\'re going to teach ME how to drive?',
        },
        {
          speaker: 'Passenger',
          thai: '......ขอลงตรงนี้ครับ',
          romanization: '......khaw long dtrong nii khrap',
          english: 'I\'ll get out here please',
        },
      ],
    },
  ],
  assessment: [
    {
      type: 'multiple_choice',
      prompt: 'ควาย as an insult means...',
      options: ['Fast', 'Stupid', 'Beautiful', 'Rich'],
      correctIndex: 1,
    },
    {
      type: 'multiple_choice',
      prompt: 'Someone calls a man จระเข้. They\'re calling him...',
      options: ['Strong', 'A womanizer', 'Tall', 'Smart'],
      correctIndex: 1,
    },
    {
      type: 'multiple_choice',
      prompt: 'How do you scream \'Hurry up you turtle!\'?',
      options: ['เร็วหน่อย ไอ้เต่า', 'ช้าหน่อย ไอ้เต่า', 'ดีมาก ไอ้เต่า', 'สวยมาก ไอ้เต่า'],
      correctIndex: 0,
    },
    {
      type: 'multiple_choice',
      prompt: 'Which animal = coward in Thai?',
      options: ['ควาย', 'ไก่', 'งู', 'หมู'],
      correctIndex: 1,
    },
    {
      type: 'multiple_choice',
      prompt: 'เขาเป็นงู means...',
      options: [
        'She is a snake (two-faced backstabber)',
        'She likes snakes',
        'She is scared of snakes',
        'She found a snake',
      ],
      correctIndex: 0,
    },
    {
      type: 'multiple_choice',
      prompt: 'แมงดา is the insult for...',
      options: [
        'A fast runner',
        'A man who lives off women\'s money',
        'A good cook',
        'A loud singer',
      ],
      correctIndex: 1,
    },
  ],
  srsItemIds: [],
}
