import type { Phrase } from './types'

// 51 conversational phrases grouped by context.
// Each phrase references word IDs and grammar pattern IDs it builds upon.

export const phrases: Phrase[] = [
  // === GREETINGS (9 phrases) ===
  {
    id: 'p_hello_male',
    thai: 'สวัสดีครับ',
    english: 'Hello (male speaker)',
    context: 'greetings',
    requiredWords: ['w_khrap'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_hello_female',
    thai: 'สวัสดีค่ะ',
    english: 'Hello (female speaker)',
    context: 'greetings',
    requiredWords: ['w_kha'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_how_are_you',
    thai: 'สบายดีไหม',
    english: 'How are you?',
    context: 'greetings',
    requiredWords: ['w_dii', 'w_mai_question'],
    requiredGrammar: ['g_q_mai'],
  },
  {
    id: 'p_im_fine',
    thai: 'สบายดี',
    english: 'I am fine.',
    context: 'greetings',
    requiredWords: ['w_dii'],
    requiredGrammar: ['g_svo_basic'],
  },
  {
    id: 'p_goodbye',
    thai: 'ลาก่อน',
    english: 'Goodbye.',
    context: 'greetings',
    requiredWords: [],
    requiredGrammar: [],
  },
  {
    id: 'p_nice_to_meet',
    thai: 'ยินดีที่ได้รู้จัก',
    english: 'Nice to meet you.',
    context: 'greetings',
    requiredWords: ['w_yin_dii', 'w_thii', 'w_dai', 'w_ruu'],
    requiredGrammar: ['g_svo_basic'],
  },
  {
    id: 'p_whats_your_name',
    thai: 'คุณชื่ออะไร',
    english: 'What is your name?',
    context: 'greetings',
    requiredWords: ['w_khun', 'w_chuea', 'w_arai'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_my_name_is',
    thai: 'ผม/ฉันชื่อ...',
    english: 'My name is...',
    context: 'greetings',
    requiredWords: ['w_pom', 'w_chan', 'w_chuea'],
    requiredGrammar: ['g_svo_basic'],
  },
  {
    id: 'p_see_you_again',
    thai: 'แล้วเจอกัน',
    english: 'See you again.',
    context: 'greetings',
    requiredWords: ['w_laeo', 'w_kat'],
    requiredGrammar: ['g_tense_laeo'],
  },

  // === FOOD (9 phrases) ===
  {
    id: 'p_menu_please',
    thai: 'ขอเมนูหน่อย',
    english: 'May I have the menu please?',
    context: 'food',
    requiredWords: ['w_khaw'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_order_this',
    thai: 'ขอสั่งอันนี้',
    english: 'I would like to order this.',
    context: 'food',
    requiredWords: ['w_khaw', 'w_an', 'w_nii'],
    requiredGrammar: ['g_clf_an'],
  },
  {
    id: 'p_is_it_spicy',
    thai: 'เผ็ดไหม',
    english: 'Is it spicy?',
    context: 'food',
    requiredWords: ['w_phet', 'w_mai_question'],
    requiredGrammar: ['g_q_mai'],
  },
  {
    id: 'p_not_spicy',
    thai: 'ไม่เผ็ด',
    english: 'Not spicy.',
    context: 'food',
    requiredWords: ['w_mai', 'w_phet'],
    requiredGrammar: ['g_neg_mai'],
  },
  {
    id: 'p_delicious',
    thai: 'อร่อยมาก',
    english: 'Very delicious!',
    context: 'food',
    requiredWords: ['w_aroi', 'w_maak'],
    requiredGrammar: ['g_adj_maak'],
  },
  {
    id: 'p_check_please',
    thai: 'เช็คบิลด้วย',
    english: 'Check please.',
    context: 'food',
    requiredWords: [],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_water_please',
    thai: 'ขอน้ำหน่อย',
    english: 'Water please.',
    context: 'food',
    requiredWords: ['w_khaw', 'w_naam'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_i_want_to_eat',
    thai: 'อยากกินข้าว',
    english: 'I want to eat rice.',
    context: 'food',
    requiredWords: ['w_yaak', 'w_gin', 'w_khaao'],
    requiredGrammar: ['g_want_yaak'],
  },
  {
    id: 'p_i_am_full',
    thai: 'อิ่มแล้ว',
    english: 'I am full already.',
    context: 'food',
    requiredWords: ['w_laeo'],
    requiredGrammar: ['g_tense_laeo'],
  },

  // === DIRECTIONS (9 phrases) ===
  {
    id: 'p_where_is',
    thai: 'อยู่ที่ไหน',
    english: 'Where is it?',
    context: 'directions',
    requiredWords: ['w_yuu', 'w_thii_nai'],
    requiredGrammar: ['g_q_what', 'g_loc_yuu'],
  },
  {
    id: 'p_turn_left',
    thai: 'เลี้ยวซ้าย',
    english: 'Turn left.',
    context: 'directions',
    requiredWords: ['w_saai'],
    requiredGrammar: ['g_loc_direction'],
  },
  {
    id: 'p_turn_right',
    thai: 'เลี้ยวขวา',
    english: 'Turn right.',
    context: 'directions',
    requiredWords: ['w_khwaa'],
    requiredGrammar: ['g_loc_direction'],
  },
  {
    id: 'p_go_straight',
    thai: 'ไปตรง',
    english: 'Go straight.',
    context: 'directions',
    requiredWords: ['w_bpai', 'w_trong'],
    requiredGrammar: ['g_loc_direction'],
  },
  {
    id: 'p_how_far',
    thai: 'ไกลไหม',
    english: 'Is it far?',
    context: 'directions',
    requiredWords: ['w_klai', 'w_mai_question'],
    requiredGrammar: ['g_q_mai'],
  },
  {
    id: 'p_its_near',
    thai: 'ใกล้',
    english: 'It is near.',
    context: 'directions',
    requiredWords: ['w_klai_near'],
    requiredGrammar: ['g_loc_yuu'],
  },
  {
    id: 'p_where_bathroom',
    thai: 'ห้องน้ำอยู่ที่ไหน',
    english: 'Where is the bathroom?',
    context: 'directions',
    requiredWords: ['w_naam', 'w_yuu', 'w_thii_nai'],
    requiredGrammar: ['g_q_what', 'g_loc_yuu'],
  },
  {
    id: 'p_on_the_left',
    thai: 'อยู่ทางซ้าย',
    english: 'It is on the left.',
    context: 'directions',
    requiredWords: ['w_yuu', 'w_saai'],
    requiredGrammar: ['g_loc_yuu'],
  },
  {
    id: 'p_stop_here',
    thai: 'จอดที่นี่',
    english: 'Stop here.',
    context: 'directions',
    requiredWords: ['w_thii', 'w_nii'],
    requiredGrammar: ['g_loc_yuu'],
  },

  // === SHOPPING (8 phrases) ===
  {
    id: 'p_how_much',
    thai: 'เท่าไร',
    english: 'How much?',
    context: 'shopping',
    requiredWords: ['w_thao_rai'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_too_expensive',
    thai: 'แพงไป',
    english: 'Too expensive.',
    context: 'shopping',
    requiredWords: ['w_phaeng', 'w_bpai'],
    requiredGrammar: ['g_adj_after'],
  },
  {
    id: 'p_can_discount',
    thai: 'ลดได้ไหม',
    english: 'Can you give a discount?',
    context: 'shopping',
    requiredWords: ['w_dai', 'w_mai_question'],
    requiredGrammar: ['g_can_dai', 'g_q_mai'],
  },
  {
    id: 'p_this_one_please',
    thai: 'เอาอันนี้',
    english: 'This one please.',
    context: 'shopping',
    requiredWords: ['w_an', 'w_nii'],
    requiredGrammar: ['g_clf_an'],
  },
  {
    id: 'p_i_want_to_buy',
    thai: 'อยากซื้อ',
    english: 'I want to buy.',
    context: 'shopping',
    requiredWords: ['w_yaak', 'w_suue'],
    requiredGrammar: ['g_want_yaak'],
  },
  {
    id: 'p_how_many_baht',
    thai: 'กี่บาท',
    english: 'How many baht?',
    context: 'shopping',
    requiredWords: ['w_kii', 'w_bat'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_its_cheap',
    thai: 'ถูก',
    english: 'It is cheap.',
    context: 'shopping',
    requiredWords: ['w_thuuk'],
    requiredGrammar: ['g_adj_after'],
  },
  {
    id: 'p_do_you_have',
    thai: 'มีไหม',
    english: 'Do you have it?',
    context: 'shopping',
    requiredWords: ['w_mii', 'w_mai_question'],
    requiredGrammar: ['g_q_mai'],
  },

  // === POLITE (8 phrases) ===
  {
    id: 'p_thank_you',
    thai: 'ขอบคุณ',
    english: 'Thank you.',
    context: 'polite',
    requiredWords: ['w_khaw', 'w_khun'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_excuse_me',
    thai: 'ขอโทษ',
    english: 'Excuse me / Sorry.',
    context: 'polite',
    requiredWords: ['w_khaw'],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_no_problem',
    thai: 'ไม่เป็นไร',
    english: 'No problem.',
    context: 'polite',
    requiredWords: ['w_mai', 'w_pen'],
    requiredGrammar: ['g_neg_mai'],
  },
  {
    id: 'p_please',
    thai: 'กรุณา',
    english: 'Please.',
    context: 'polite',
    requiredWords: [],
    requiredGrammar: ['g_polite_statement'],
  },
  {
    id: 'p_youre_welcome',
    thai: 'ไม่เป็นไรครับ/ค่ะ',
    english: 'You are welcome.',
    context: 'polite',
    requiredWords: ['w_mai', 'w_pen', 'w_khrap', 'w_kha'],
    requiredGrammar: ['g_polite_statement', 'g_neg_mai'],
  },
  {
    id: 'p_help_me',
    thai: 'ช่วยด้วย',
    english: 'Help me!',
    context: 'polite',
    requiredWords: [],
    requiredGrammar: [],
  },
  {
    id: 'p_wait_moment',
    thai: 'รอสักครู่',
    english: 'Wait a moment.',
    context: 'polite',
    requiredWords: [],
    requiredGrammar: [],
  },
  {
    id: 'p_never_mind',
    thai: 'ช่างเถอะ',
    english: 'Never mind.',
    context: 'polite',
    requiredWords: [],
    requiredGrammar: [],
  },

  // === QUESTIONS (8 phrases) ===
  {
    id: 'p_what_is_this',
    thai: 'นี่อะไร',
    english: 'What is this?',
    context: 'questions',
    requiredWords: ['w_nii', 'w_arai'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_what_time',
    thai: 'กี่โมง',
    english: 'What time is it?',
    context: 'questions',
    requiredWords: ['w_kii', 'w_moong'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_speak_english',
    thai: 'พูดภาษาอังกฤษได้ไหม',
    english: 'Can you speak English?',
    context: 'questions',
    requiredWords: ['w_phuut', 'w_dai', 'w_mai_question'],
    requiredGrammar: ['g_can_dai', 'g_q_mai'],
  },
  {
    id: 'p_where_from',
    thai: 'มาจากที่ไหน',
    english: 'Where are you from?',
    context: 'questions',
    requiredWords: ['w_maa', 'w_thii_nai'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_how_to_say',
    thai: 'ภาษาไทยพูดว่าอะไร',
    english: 'How do you say it in Thai?',
    context: 'questions',
    requiredWords: ['w_phuut', 'w_arai'],
    requiredGrammar: ['g_q_what'],
  },
  {
    id: 'p_understand',
    thai: 'เข้าใจไหม',
    english: 'Do you understand?',
    context: 'questions',
    requiredWords: ['w_khao', 'w_jai', 'w_mai_question'],
    requiredGrammar: ['g_q_mai'],
  },
  {
    id: 'p_dont_understand',
    thai: 'ไม่เข้าใจ',
    english: 'I don\'t understand.',
    context: 'questions',
    requiredWords: ['w_mai', 'w_khao', 'w_jai'],
    requiredGrammar: ['g_neg_mai'],
  },
  {
    id: 'p_say_again',
    thai: 'พูดอีกทีได้ไหม',
    english: 'Can you say that again?',
    context: 'questions',
    requiredWords: ['w_phuut', 'w_dai', 'w_mai_question'],
    requiredGrammar: ['g_can_dai', 'g_q_mai'],
  },
]
