import type { RichLesson } from '../lessonTypes'

// Phase 2: Expanding the Alphabet (Lessons 6-10)

export const phase2Lessons: RichLesson[] = [
  // === LESSON 6: Aspirated Consonants ===
  {
    id: 'R06',
    title: 'Aspirated Consonants',
    goal: 'Learn 3 high-class consonants ข (kaw), ส (saw), ถ (taw). Note they have a "puff of air" (aspirated).',
    phase: 'vowels',
    order: 5,
    difficulty: 'beginner',
    prerequisites: ['R05'],
    steps: [
      {
        kind: 'text',
        content:
          'Time to expand your consonant repertoire. These three consonants belong to the **high class** and are all **aspirated** -- pronounced with a noticeable puff of air.\n\nCompare: ก (gaw) has no puff of air, while ข (kaw) does. Both are \'k-like\' sounds, but they belong to different classes.',
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ข',
            romanization: 'kaw',
            english: '"k" sound aspirated, as in "kite"',
            detail: 'Keyword: ไข่ khai = egg. High class.',
            audioText: 'ขอ',
          },
          {
            thai: 'ส',
            romanization: 'saw',
            english: '"s" sound as in "sun"',
            detail: 'Keyword: เสือ suea = tiger. High class.',
            audioText: 'สอ',
          },
          {
            thai: 'ถ',
            romanization: 'taw',
            english: '"t" sound aspirated, as in "top"',
            detail: 'Keyword: ถุง thung = bag. High class.',
            audioText: 'ถอ',
          },
        ],
      },
      {
        kind: 'rule',
        rule: 'Aspirated consonants are pronounced with a puff of air. Hold your hand near your mouth: ก (gaw) = no puff, ข (kaw) = puff. Same principle: ต (dtaw) = no puff, ถ (taw) = puff.',
        examples: [
          { thai: 'ก', romanization: 'gaw', english: 'No puff (mid class)' },
          { thai: 'ข', romanization: 'kaw', english: 'Puff of air (high class)' },
          { thai: 'ต', romanization: 'dtaw', english: 'No puff (mid class)' },
          { thai: 'ถ', romanization: 'taw', english: 'Puff of air (high class)' },
        ],
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ขา',
            romanization: 'khaa',
            english: 'leg',
            detail: 'ข + -า = khaa',
            audioText: 'ขา',
          },
          {
            thai: 'สี',
            romanization: 'sii',
            english: 'color',
            detail: 'ส + -ี = sii',
            audioText: 'สี',
          },
          {
            thai: 'ถา',
            romanization: 'thaa',
            english: 'to apply',
            detail: 'ถ + -า = thaa',
            audioText: 'ถา',
          },
        ],
      },
      {
        kind: 'example',
        title: 'Reading ขา: aspirated consonant + vowel',
        steps: [
          { label: 'Consonant', content: 'ข = kaw (aspirated "k" sound, high class)' },
          { label: 'Vowel', content: '-า = aa (long, written after)' },
          { label: 'Combine', content: 'kh + aa = khaa' },
          { label: 'Result', content: 'ขา = khaa (leg)' },
        ],
      },
      {
        kind: 'practice',
        exercises: [
          {
            type: 'multiple_choice',
            prompt: 'What sound does ข make?',
            promptThai: 'ข',
            options: ['gaw', 'kaw', 'saw', 'taw'],
            correctIndex: 1,
            audioText: 'ขอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read สี?',
            promptThai: 'สี',
            options: ['saa', 'sii', 'suu', 'see'],
            correctIndex: 1,
            audioText: 'สี',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read ขา?',
            promptThai: 'ขา',
            options: ['gaa', 'khaa', 'saa', 'thaa'],
            correctIndex: 1,
            audioText: 'ขา',
          },
          {
            type: 'multiple_choice',
            prompt: 'What sound does ถ make?',
            promptThai: 'ถ',
            options: ['dtaw', 'saw', 'kaw', 'taw'],
            correctIndex: 3,
            audioText: 'ถอ',
          },
          {
            type: 'match',
            pairs: [
              { left: 'ข', right: 'kaw' },
              { left: 'ส', right: 'saw' },
              { left: 'ถ', right: 'taw' },
            ],
          },
        ],
      },
    ],
    assessment: [
      {
        type: 'multiple_choice',
        prompt: 'What sound does ข make?',
        promptThai: 'ข',
        options: ['kaw', 'gaw', 'saw', 'taw'],
        correctIndex: 0,
        audioText: 'ขอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does ส make?',
        promptThai: 'ส',
        options: ['saw', 'kaw', 'taw', 'daw'],
        correctIndex: 0,
        audioText: 'สอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read ขา?',
        promptThai: 'ขา',
        options: ['khaa', 'saa', 'thaa', 'gaa'],
        correctIndex: 0,
        audioText: 'ขา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read สี?',
        promptThai: 'สี',
        options: ['sii', 'saa', 'suu', 'see'],
        correctIndex: 0,
        audioText: 'สี',
      },
      {
        type: 'multiple_choice',
        prompt: 'ก (gaw) has no puff of air. ข (kaw) does. What is this difference called?',
        options: ['Tonal', 'Aspirated vs unaspirated', 'Long vs short', 'High vs low'],
        correctIndex: 1,
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read ถา?',
        promptThai: 'ถา',
        options: ['thaa', 'khaa', 'saa', 'dtaa'],
        correctIndex: 0,
        audioText: 'ถา',
      },
    ],
    srsItemIds: ['khor_khai', 'sor_suea', 'thor_thung', 'w_khaa', 'w_sii', 'w_thaa'],
    skillPreview: {
      heading: 'You\'ll read aspirated consonant syllables',
      examples: [
        { thai: 'ขา', romanization: 'khaa', meaning: 'leg' },
        { thai: 'สี', romanization: 'sii', meaning: 'color' },
        { thai: 'ถา', romanization: 'thaa', meaning: 'to apply' },
      ],
    },
  },

  // === LESSON 7: Common Consonants ===
  {
    id: 'R07',
    title: 'Common Consonants',
    goal: 'Learn 3 very common low-class consonants ค (kaw), น (naw), ม (maw). First words with final consonants.',
    phase: 'vowels',
    order: 6,
    difficulty: 'beginner',
    prerequisites: ['R06'],
    steps: [
      {
        kind: 'text',
        content:
          'Three extremely common consonants from the **low class**. These sounds are familiar from English. After this lesson, you can read words with a consonant at the end -- like กิน (gin, to eat).',
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ค',
            romanization: 'kaw',
            english: '"k" aspirated, same sound as ข but low class',
            detail: 'Keyword: ควาย kwaai = buffalo. Low class.',
            audioText: 'คอ',
          },
          {
            thai: 'น',
            romanization: 'naw',
            english: '"n" as in "no"',
            detail: 'Keyword: หนู nuu = mouse. Low class.',
            audioText: 'นอ',
          },
          {
            thai: 'ม',
            romanization: 'maw',
            english: '"m" as in "mom"',
            detail: 'Keyword: ม้า maa = horse. Low class.',
            audioText: 'มอ',
          },
        ],
      },
      {
        kind: 'rule',
        rule: 'ค (low class) and ข (high class) make the same \'k\' (aspirated) sound but belong to different classes. For now, just recognize the sounds -- the class difference matters for tones, which come later.',
        examples: [
          { thai: 'ขา', romanization: 'khaa (high class)', english: 'leg' },
          { thai: 'คา', romanization: 'khaa (low class)', english: 'to be stuck' },
        ],
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'มา',
            romanization: 'maa',
            english: 'to come',
            detail: 'ม + -า = maa',
            audioText: 'มา',
          },
          {
            thai: 'นา',
            romanization: 'naa',
            english: 'rice field',
            detail: 'น + -า = naa',
            audioText: 'นา',
          },
          {
            thai: 'กิน',
            romanization: 'gin',
            english: 'to eat',
            detail: 'ก + -ิ + น -- first word with a final consonant',
            audioText: 'กิน',
          },
        ],
      },
      {
        kind: 'example',
        title: 'Reading a word with a final consonant: กิน',
        steps: [
          { label: 'Consonant', content: 'ก = gaw (g sound)' },
          { label: 'Vowel', content: '-ิ = i (short, written above)' },
          { label: 'Final consonant', content: 'น = n (at the end)' },
          { label: 'Combine', content: 'g + i + n = gin' },
          { label: 'Result', content: 'กิน = gin = to eat. The น at the end closes the syllable.' },
        ],
      },
      {
        kind: 'practice',
        exercises: [
          {
            type: 'multiple_choice',
            prompt: 'What sound does ค make?',
            promptThai: 'ค',
            options: ['gaw', 'kaw', 'naw', 'maw'],
            correctIndex: 1,
            audioText: 'คอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'What sound does น make?',
            promptThai: 'น',
            options: ['maw', 'naw', 'kaw', 'raw'],
            correctIndex: 1,
            audioText: 'นอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read มา?',
            promptThai: 'มา',
            options: ['naa', 'kaa', 'maa', 'raa'],
            correctIndex: 2,
            audioText: 'มา',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read กิน?',
            promptThai: 'กิน',
            options: ['giin', 'gin', 'gan', 'gun'],
            correctIndex: 1,
            audioText: 'กิน',
          },
          {
            type: 'match',
            pairs: [
              { left: 'ค', right: 'kaw' },
              { left: 'น', right: 'naw' },
              { left: 'ม', right: 'maw' },
            ],
          },
        ],
      },
    ],
    assessment: [
      {
        type: 'multiple_choice',
        prompt: 'What sound does ค make?',
        promptThai: 'ค',
        options: ['kaw', 'gaw', 'naw', 'maw'],
        correctIndex: 0,
        audioText: 'คอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does น make?',
        promptThai: 'น',
        options: ['naw', 'maw', 'kaw', 'raw'],
        correctIndex: 0,
        audioText: 'นอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does ม make?',
        promptThai: 'ม',
        options: ['maw', 'naw', 'kaw', 'raw'],
        correctIndex: 0,
        audioText: 'มอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read มา?',
        promptThai: 'มา',
        options: ['maa', 'naa', 'kaa', 'raa'],
        correctIndex: 0,
        audioText: 'มา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read นา?',
        promptThai: 'นา',
        options: ['naa', 'maa', 'kaa', 'gaa'],
        correctIndex: 0,
        audioText: 'นา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read กิน?',
        promptThai: 'กิน',
        options: ['giin', 'gin', 'gan', 'gun'],
        correctIndex: 1,
        audioText: 'กิน',
      },
    ],
    srsItemIds: ['khor_khwaai', 'nor_nuu', 'mor_maa', 'w_maa', 'w_naa', 'w_gin'],
    skillPreview: {
      heading: 'You\'ll read words with final consonants',
      examples: [
        { thai: 'กิน', romanization: 'gin', meaning: 'to eat' },
        { thai: 'มา', romanization: 'maa', meaning: 'to come' },
        { thai: 'นา', romanization: 'naa', meaning: 'rice field' },
      ],
    },
  },

  // === LESSON 8: More Consonants ===
  {
    id: 'R08',
    title: 'More Consonants',
    goal: 'Learn 4 common consonants ร (raw), ล (law), ว (waw), ง (ngaw). All simple sounds.',
    phase: 'vowels',
    order: 7,
    difficulty: 'beginner',
    prerequisites: ['R07'],
    steps: [
      {
        kind: 'text',
        content:
          'Four more consonants, all with sounds similar to English (except ง which makes the \'ng\' sound as at the END of \'sing\' -- but in Thai it can START a syllable).',
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ร',
            romanization: 'raw',
            english: '"r" rolled/flapped',
            detail: 'Keyword: เรือ ruea = boat. Low class.',
            audioText: 'รอ',
          },
          {
            thai: 'ล',
            romanization: 'law',
            english: '"l" as in "love"',
            detail: 'Keyword: ลิง ling = monkey. Low class.',
            audioText: 'ลอ',
          },
          {
            thai: 'ว',
            romanization: 'waw',
            english: '"w" as in "water"',
            detail: 'Keyword: แหวน waen = ring. Low class.',
            audioText: 'วอ',
          },
          {
            thai: 'ง',
            romanization: 'ngaw',
            english: '"ng" as in "sing"',
            detail: 'Keyword: งู nguu = snake. Low class.',
            audioText: 'งอ',
          },
        ],
      },
      {
        kind: 'rule',
        rule: 'The consonant ง (ngaw) makes the "ng" sound you hear at the END of English words like "sing" or "ring." In Thai, this sound can also START a syllable -- something English never does. Try saying "ng" without any vowel before it.',
        examples: [
          { thai: 'งู', romanization: 'nguu', english: 'snake -- starts with "ng"' },
          { thai: 'งา', romanization: 'ngaa', english: 'sesame / ivory -- starts with "ng"' },
        ],
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'วัน',
            romanization: 'wan',
            english: 'day',
            detail: 'ว + -ั + น = wan',
            audioText: 'วัน',
          },
          {
            thai: 'งู',
            romanization: 'nguu',
            english: 'snake',
            detail: 'ง + -ู = nguu',
            audioText: 'งู',
          },
          {
            thai: 'รู',
            romanization: 'ruu',
            english: 'hole',
            detail: 'ร + -ู = ruu',
            audioText: 'รู',
          },
        ],
      },
      {
        kind: 'practice',
        exercises: [
          {
            type: 'multiple_choice',
            prompt: 'What sound does ร make?',
            promptThai: 'ร',
            options: ['law', 'raw', 'waw', 'ngaw'],
            correctIndex: 1,
            audioText: 'รอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'What sound does ง make?',
            promptThai: 'ง',
            options: ['naw', 'maw', 'ngaw', 'waw'],
            correctIndex: 2,
            audioText: 'งอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read งู?',
            promptThai: 'งู',
            options: ['nuu', 'nguu', 'muu', 'wuu'],
            correctIndex: 1,
            audioText: 'งู',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read วา?',
            promptThai: 'วา',
            options: ['raa', 'laa', 'waa', 'ngaa'],
            correctIndex: 2,
            audioText: 'วา',
          },
          {
            type: 'match',
            pairs: [
              { left: 'ร', right: 'raw' },
              { left: 'ล', right: 'law' },
              { left: 'ว', right: 'waw' },
              { left: 'ง', right: 'ngaw' },
            ],
          },
        ],
      },
    ],
    assessment: [
      {
        type: 'multiple_choice',
        prompt: 'What sound does ร make?',
        promptThai: 'ร',
        options: ['raw', 'law', 'waw', 'ngaw'],
        correctIndex: 0,
        audioText: 'รอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does ง make?',
        promptThai: 'ง',
        options: ['ngaw', 'naw', 'maw', 'waw'],
        correctIndex: 0,
        audioText: 'งอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read วา?',
        promptThai: 'วา',
        options: ['waa', 'raa', 'laa', 'ngaa'],
        correctIndex: 0,
        audioText: 'วา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read ลา?',
        promptThai: 'ลา',
        options: ['laa', 'raa', 'waa', 'ngaa'],
        correctIndex: 0,
        audioText: 'ลา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read งู?',
        promptThai: 'งู',
        options: ['nguu', 'nuu', 'muu', 'wuu'],
        correctIndex: 0,
        audioText: 'งู',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read รี?',
        promptThai: 'รี',
        options: ['rii', 'lii', 'wii', 'ngii'],
        correctIndex: 0,
        audioText: 'รี',
      },
    ],
    srsItemIds: ['ror_ruea', 'lor_ling', 'wor_waen', 'ngor_nguu', 'w_ruu', 'w_wan'],
    skillPreview: {
      heading: 'You\'ll read more consonant patterns',
      examples: [
        { thai: 'วัน', romanization: 'wan', meaning: 'day' },
        { thai: 'งู', romanization: 'nguu', meaning: 'snake' },
        { thai: 'รู้', romanization: 'rúu', meaning: 'to know' },
      ],
    },
  },

  // === LESSON 9: Special Vowels ===
  {
    id: 'R09',
    title: 'Special Vowels',
    goal: 'Learn 3 special vowel forms: -ำ (am), ไ- (ai), -ั (short a with final consonant). Unlock high-frequency words.',
    phase: 'vowels',
    order: 8,
    difficulty: 'beginner',
    prerequisites: ['R08'],
    steps: [
      {
        kind: 'text',
        content:
          'Some Thai vowels are "compound" -- they represent a vowel plus a final consonant sound combined into one symbol. These special forms appear in many of the most common Thai words.',
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: '-ำ',
            romanization: 'am',
            english: 'Short "a" + "m" combined',
            detail: 'กำ = gam. The "m" ending is built into the vowel symbol.',
            audioText: 'กำ',
          },
          {
            thai: 'ไ-',
            romanization: 'ai',
            english: '"ai" as in "Thai"',
            detail: 'Written before the consonant: ไก = gai.',
            audioText: 'ไก',
          },
          {
            thai: '-ั',
            romanization: 'a',
            english: 'Short "a" (must have a final consonant)',
            detail: 'กัน = gan. The mark -ั above means short "a" and always needs a final consonant.',
            audioText: 'กัน',
          },
        ],
      },
      {
        kind: 'rule',
        rule: 'The vowel -ำ always includes the sound "m" at the end -- it is a complete syllable ender. The vowel ไ- is the "ai" sound, familiar from the word "Thai" itself. The mark -ั (mai han akat) represents a short "a" but always requires a final consonant after it.',
        examples: [
          { thai: 'กำ', romanization: 'gam', english: 'g + am (the "m" is in the vowel)' },
          { thai: 'ไก', romanization: 'gai', english: 'g + ai (vowel before consonant)' },
          { thai: 'กัน', romanization: 'gan', english: 'g + a + n (needs final consonant)' },
        ],
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ไป',
            romanization: 'bpai',
            english: 'to go',
            detail: 'ป + ไ- = bpai. One of the most common Thai words.',
            audioText: 'ไป',
          },
          {
            thai: 'กำ',
            romanization: 'gam',
            english: 'to grip',
            detail: 'ก + -ำ = gam. The vowel -ำ includes the "m" ending.',
            audioText: 'กำ',
          },
          {
            thai: 'กัน',
            romanization: 'gan',
            english: 'together / each other',
            detail: 'ก + -ั + น = gan. The -ั needs a final consonant (น).',
            audioText: 'กัน',
          },
        ],
      },
      {
        kind: 'practice',
        exercises: [
          {
            type: 'multiple_choice',
            prompt: 'How do you read ไก?',
            promptThai: 'ไก',
            options: ['gaa', 'gam', 'gai', 'gii'],
            correctIndex: 2,
            audioText: 'ไก',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read กำ?',
            promptThai: 'กำ',
            options: ['gaa', 'gam', 'gai', 'gan'],
            correctIndex: 1,
            audioText: 'กำ',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read ไป?',
            promptThai: 'ไป',
            options: ['bpam', 'bpaa', 'bpai', 'bpan'],
            correctIndex: 2,
            audioText: 'ไป',
          },
          {
            type: 'multiple_choice',
            prompt: 'What sound does -ำ always end with?',
            options: ['n', 'ng', 'm', 'k'],
            correctIndex: 2,
          },
          {
            type: 'match',
            pairs: [
              { left: '-ำ', right: 'am (includes "m")' },
              { left: 'ไ-', right: 'ai (before consonant)' },
              { left: '-ั', right: 'a (needs final consonant)' },
            ],
          },
        ],
      },
    ],
    assessment: [
      {
        type: 'multiple_choice',
        prompt: 'How do you read ไก?',
        promptThai: 'ไก',
        options: ['gai', 'gam', 'gaa', 'gan'],
        correctIndex: 0,
        audioText: 'ไก',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read กำ?',
        promptThai: 'กำ',
        options: ['gam', 'gai', 'gan', 'gaa'],
        correctIndex: 0,
        audioText: 'กำ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does -ำ always end with?',
        options: ['n', 'ng', 'm', 'k'],
        correctIndex: 2,
      },
      {
        type: 'multiple_choice',
        prompt: 'Where is ไ- written?',
        options: ['After the consonant', 'Above the consonant', 'Before the consonant', 'Below the consonant'],
        correctIndex: 2,
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read ไป?',
        promptThai: 'ไป',
        options: ['bpai', 'bpam', 'bpaa', 'bpan'],
        correctIndex: 0,
        audioText: 'ไป',
      },
      {
        type: 'multiple_choice',
        prompt: '-ั must always have what after it?',
        options: ['A tone mark', 'A final consonant', 'Another vowel', 'Nothing'],
        correctIndex: 1,
      },
    ],
    srsItemIds: ['sara_am', 'sara_ai_maimalai', 'mai_han_akat', 'w_bpai', 'w_kam', 'w_gan'],
    skillPreview: {
      heading: 'You\'ll read special vowel patterns',
      examples: [
        { thai: 'ไป', romanization: 'bpai', meaning: 'to go' },
        { thai: 'น้ำ', romanization: 'náam', meaning: 'water' },
        { thai: 'กัน', romanization: 'gan', meaning: 'together' },
      ],
    },
  },

  // === LESSON 10: Consonant Classes (Introduction) ===
  {
    id: 'R10',
    title: 'Consonant Classes',
    goal: 'Learn 4 more consonants ท (taw), ช (chaw), ย (yaw), ผ (paw). Introduce the concept that consonants belong to classes (mid/high/low) that affect tone.',
    phase: 'vowels',
    order: 9,
    difficulty: 'beginner',
    prerequisites: ['R09'],
    steps: [
      {
        kind: 'text',
        content:
          'Four more consonants, and an important concept: every Thai consonant belongs to one of three **classes** -- mid, high, or low. The class affects the **tone** of a syllable. You will learn the full tone system in Phase 4 -- for now, just notice how the same vowel sounds different with different consonant classes.',
      },
      {
        kind: 'info_card',
        items: [
          {
            thai: 'ท',
            romanization: 'taw',
            english: 'Aspirated "t", low class',
            detail: 'Keyword: ธง thong = flag. Low class.',
            audioText: 'ทอ',
          },
          {
            thai: 'ช',
            romanization: 'chaw',
            english: '"ch" as in "chair", low class',
            detail: 'Keyword: ช้าง chaang = elephant. Low class.',
            audioText: 'ชอ',
          },
          {
            thai: 'ย',
            romanization: 'yaw',
            english: '"y" as in "yes", low class',
            detail: 'Keyword: ยักษ์ yak = giant. Low class.',
            audioText: 'ยอ',
          },
          {
            thai: 'ผ',
            romanization: 'paw',
            english: 'Aspirated "p", high class',
            detail: 'Keyword: ผึ้ง pueng = bee. High class.',
            audioText: 'ผอ',
          },
        ],
      },
      {
        kind: 'table',
        title: 'The Three Consonant Classes',
        headers: ['Class', 'Description', 'Consonants You Know'],
        rows: [
          ['Mid', '9 consonants, simplest tone rules', 'ก จ ด ต บ ป อ'],
          ['High', 'Aspirated, rising default tone', 'ข ส ถ ผ'],
          ['Low', 'Largest group', 'ค น ม ร ล ว ง ท ช ย'],
        ],
      },
      {
        kind: 'rule',
        rule: 'Same sound, different class, different tone. กา (mid class ก) has a mid tone. ขา (high class ข) has a rising tone. Both use the same vowel -า. The consonant class changes the tone.',
        examples: [
          { thai: 'กา', romanization: 'gaa (mid tone)', english: 'Mid class ก' },
          { thai: 'ขา', romanization: 'khǎa (rising tone)', english: 'High class ข' },
          { thai: 'คา', romanization: 'khaa (mid tone)', english: 'Low class ค' },
        ],
      },
      {
        kind: 'practice',
        exercises: [
          {
            type: 'multiple_choice',
            prompt: 'What sound does ท make?',
            promptThai: 'ท',
            options: ['dtaw', 'taw', 'chaw', 'yaw'],
            correctIndex: 1,
            audioText: 'ทอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'What sound does ช make?',
            promptThai: 'ช',
            options: ['saw', 'taw', 'chaw', 'yaw'],
            correctIndex: 2,
            audioText: 'ชอ',
          },
          {
            type: 'multiple_choice',
            prompt: 'How do you read ชา?',
            promptThai: 'ชา',
            options: ['saa', 'thaa', 'chaa', 'yaa'],
            correctIndex: 2,
            audioText: 'ชา',
          },
          {
            type: 'multiple_choice',
            prompt: 'How many consonant classes does Thai have?',
            options: ['2', '3', '4', '5'],
            correctIndex: 1,
          },
          {
            type: 'match',
            pairs: [
              { left: 'ท', right: 'taw (low class)' },
              { left: 'ช', right: 'chaw (low class)' },
              { left: 'ย', right: 'yaw (low class)' },
              { left: 'ผ', right: 'paw (high class)' },
            ],
          },
        ],
      },
    ],
    assessment: [
      {
        type: 'multiple_choice',
        prompt: 'What sound does ท make?',
        promptThai: 'ท',
        options: ['taw', 'dtaw', 'chaw', 'yaw'],
        correctIndex: 0,
        audioText: 'ทอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does ช make?',
        promptThai: 'ช',
        options: ['chaw', 'saw', 'taw', 'yaw'],
        correctIndex: 0,
        audioText: 'ชอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'What sound does ย make?',
        promptThai: 'ย',
        options: ['yaw', 'waw', 'raw', 'law'],
        correctIndex: 0,
        audioText: 'ยอ',
      },
      {
        type: 'multiple_choice',
        prompt: 'How do you read ชา?',
        promptThai: 'ชา',
        options: ['chaa', 'saa', 'thaa', 'yaa'],
        correctIndex: 0,
        audioText: 'ชา',
      },
      {
        type: 'multiple_choice',
        prompt: 'How many consonant classes does Thai have?',
        options: ['2', '3', '4', '5'],
        correctIndex: 1,
      },
      {
        type: 'multiple_choice',
        prompt: 'กา has mid tone (mid class). ขา has rising tone (high class). What determines the tone difference?',
        options: [
          'The vowel',
          'The consonant class',
          'The word length',
          'The spelling',
        ],
        correctIndex: 1,
      },
    ],
    srsItemIds: ['thor_thong', 'chor_chaang', 'yor_yak', 'phor_phueng', 'w_tham', 'w_chaa', 'w_yaa'],
    skillPreview: {
      heading: 'You\'ll understand consonant classes',
      examples: [
        { thai: 'กา', romanization: 'gaa', meaning: 'crow (mid class)' },
        { thai: 'ขา', romanization: 'khǎa', meaning: 'leg (high class)' },
        { thai: 'คา', romanization: 'khaa', meaning: 'stuck (low class)' },
      ],
    },
  },
]
